### ISSUE TITLE
Request for simple instructions

### ISSUE THREAD

**Issue by GenTxt** [26medias/context-aware-markov-chains#2]
Hi,
Your markov application is very intriguing. I'm familiar with markov and rnn programs
in python and torch etc. but I'm having difficulty generating output with this version.

I would like to train models using my corpus files and would appreciate simple step-by-step
instructions.

This is what I have working on linux ubuntu:

1. node.js and Neo4j including all dependencies (npm in win 7 threw too many errors)

2. http://localhost:7474/browser/ 

Interface loads and asks for password (running on firefox)

:server connect
Connected to Neo4j

Nice to meet you.

    You are connected as user neo4j
    to the server http://localhost:7474/browser/

    Connection credentials are stored in your web browser.

3. Drag and drop Neo4j.grass style sheet accepted

4. I open a terminal window and run: node test.js

Starting Depth 1
Generating the ngrams
Stringification of 258278 ngrams
Graphing
Starting Depth 2
Generating the ngrams
Stringification of 258277 ngrams
Graphing
Starting Depth 3
Generating the ngrams
Stringification of 258276 ngrams
Graphing
Starting Depth 4
Generating the ngrams
Stringification of 258275 ngrams
Graphing
Starting Depth 5
Generating the ngrams
Stringification of 258274 ngrams
Graphing
Reading the N-grams... [====================] 100% [1025/1025] 0.0s
Reading the N-grams... [====================] 100% [1026/1025] 0.0s

5. Terminal above finishes and there's a Neo4j notice that there's a database waiting but it's not accessible. Instructed to make a new server connection.

I do but it connects to ??? There isn't a db file that I can see in the interface and no output file is generated.

What am I doing wrong?  I would like to generate text files from my corpus and would appreciate knowing the steps.

Thanks

**Comment by 26medias** [comment]
Hi,

Looks like it might be a credential issues.
Make sure neo4j is setup with username "neo4j" and password "pwd".

Let me know if that works.

**Comment by GenTxt** [comment]
Working now thanks
